# _config.yml
title: My Notes
description: My personal notes and thoughts
baseurl: ""
url: "https://thinkingjet.github.io"

# Build settings
markdown: kramdown
permalink: /:title/

# Collections
collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"

plugins:
  - jekyll-feed
  - jekyll-seo-tag