# _config.yml
title: My Notes
description: Digital Garden
url: "https://thinkingjet.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

# If you're using GitHub Pages, add:
github: [metadata]